# このファイルはGitHub Actionsのマトリックスを生成します。
# シンプルなボードとシールドの組み合わせの場合、トップレベルのboardと
# shield配列に追加し、より細かい制御が必要な場合は、
# `include`プロパティに個々のボードとシールドの組み合わせを追加します。
# また、ビルドコマンドにフラグを渡すために`cmake-args`プロパティを使用したり、
# ビルド出力を区別するために`artifact-name`を割り当てることもできます：
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: bt60_v1
    artifact-name: bt60_v1_build
  - board: bt65_v1
    artifact-name: bt65_v1_build
  - board: seeeduino_xiao
    shield: nice_view
    artifact-name: seeeduino_xiao_nice_view_build
  - board: seeeduino_xiao_ble
    shield: nice_view
    artifact-name: seeeduino_xiao_ble_nice_view_build
  - board: bt65_v1
    artifact-name: bt65_v1_build_2
